import { useState, useCallback, useMemo } from "react";
import { useLocation } from "wouter";
import { ParticleCanvas } from "@/components/ParticleCanvas";
import { DEFAULT_CONFIG, type ParticleConfig } from "@/lib/particles/engine";
import { DEMO_PRESETS } from "@/lib/particles/presets";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogDescription } from "@/components/ui/dialog";
import {
  Sparkles,
  ArrowLeft,
  Save,
  Download,
  Plus,
  Trash2,
  Play,
  Pause,
  RotateCcw,
  Globe,
  Paintbrush,
  Wind,
  Orbit,
  Copy,
  Check,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { apiRequest } from "@/lib/queryClient";

interface SequenceStop {
  id: string;
  config: Partial<ParticleConfig>;
  backgroundColor: string;
  duration: number;
  transition: "fade" | "instant" | "flash";
  transitionDuration: number;
}

export default function BuilderPage() {
  const [, navigate] = useLocation();
  const { toast } = useToast();

  // Core state
  const [config, setConfig] = useState<Partial<ParticleConfig>>({ ...DEFAULT_CONFIG });
  const [backgroundColor, setBackgroundColor] = useState("#0a0812");
  const [projectName, setProjectName] = useState("Untitled Project");
  const [sourceUrl, setSourceUrl] = useState("");
  const [showUrlInput, setShowUrlInput] = useState(false);

  // Sequence state
  const [sequence, setSequence] = useState<SequenceStop[]>([]);
  const [activeSequenceIndex, setActiveSequenceIndex] = useState(-1);
  const [isPlayingSequence, setIsPlayingSequence] = useState(false);

  // Export state
  const [showExport, setShowExport] = useState(false);
  const [copied, setCopied] = useState(false);

  // Current active config (either the main config or the sequence stop)
  const activeConfig = useMemo(() => {
    if (activeSequenceIndex >= 0 && sequence[activeSequenceIndex]) {
      return sequence[activeSequenceIndex].config;
    }
    return config;
  }, [config, sequence, activeSequenceIndex]);

  const activeBg = useMemo(() => {
    if (activeSequenceIndex >= 0 && sequence[activeSequenceIndex]) {
      return sequence[activeSequenceIndex].backgroundColor;
    }
    return backgroundColor;
  }, [backgroundColor, sequence, activeSequenceIndex]);

  const updateConfig = useCallback((updates: Partial<ParticleConfig>) => {
    if (activeSequenceIndex >= 0) {
      setSequence(prev => prev.map((s, i) =>
        i === activeSequenceIndex ? { ...s, config: { ...s.config, ...updates } } : s
      ));
    } else {
      setConfig(prev => ({ ...prev, ...updates }));
    }
  }, [activeSequenceIndex]);

  const addToSequence = () => {
    const newStop: SequenceStop = {
      id: `stop-${Date.now()}`,
      config: { ...DEFAULT_CONFIG },
      backgroundColor: "#0a0812",
      duration: 5,
      transition: "fade",
      transitionDuration: 1.5,
    };
    setSequence(prev => [...prev, newStop]);
    setActiveSequenceIndex(sequence.length);
  };

  const removeFromSequence = (index: number) => {
    setSequence(prev => prev.filter((_, i) => i !== index));
    if (activeSequenceIndex >= index) {
      setActiveSequenceIndex(Math.max(-1, activeSequenceIndex - 1));
    }
  };

  const loadPreset = (presetId: string) => {
    const preset = DEMO_PRESETS.find(p => p.id === presetId);
    if (preset) {
      updateConfig(preset.config);
      if (activeSequenceIndex >= 0) {
        setSequence(prev => prev.map((s, i) =>
          i === activeSequenceIndex ? { ...s, backgroundColor: preset.backgroundColor } : s
        ));
      } else {
        setBackgroundColor(preset.backgroundColor);
      }
    }
  };

  const generateExportCode = () => {
    const cfg = activeConfig;
    return `// LandingLabs — Three.js Particle Background
// Generated by LandingLabs (https://landinglabs.dev)
// Paste this into your project and customize as needed.

import * as THREE from 'three';

(function initParticleBackground() {
  // === Configuration ===
  const CONFIG = ${JSON.stringify(cfg, null, 4)};
  
  const BG_COLOR = '${activeBg}';

  // === Setup ===
  const container = document.getElementById('particle-bg');
  // Create a container div in your HTML: <div id="particle-bg" style="position:fixed;inset:0;z-index:-1;"></div>
  
  if (!container) {
    console.warn('LandingLabs: No #particle-bg container found. Create a div with id="particle-bg".');
    return;
  }

  container.style.backgroundColor = BG_COLOR;

  const scene = new THREE.Scene();
  const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);
  camera.position.z = 50;

  const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
  renderer.setSize(window.innerWidth, window.innerHeight);
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setClearColor(0x000000, 0);
  container.appendChild(renderer.domElement);

  // === Particles ===
  const count = CONFIG.count || 2000;
  const geometry = new THREE.BufferGeometry();
  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 3);
  const c1 = new THREE.Color(CONFIG.color || '#00d4ff');
  const c2 = new THREE.Color(CONFIG.gradientEnd || CONFIG.color || '#00d4ff');

  for (let i = 0; i < count; i++) {
    const i3 = i * 3;
    const t = i / count;
    // Position particles based on pattern
    positions[i3] = (Math.random() - 0.5) * 60;
    positions[i3 + 1] = (Math.random() - 0.5) * 60;
    positions[i3 + 2] = (Math.random() - 0.5) * 40;
    // Gradient color
    const lerpColor = c1.clone().lerp(c2, t + (Math.random() - 0.5) * 0.3);
    colors[i3] = lerpColor.r;
    colors[i3 + 1] = lerpColor.g;
    colors[i3 + 2] = lerpColor.b;
  }

  geometry.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  geometry.setAttribute('color', new THREE.BufferAttribute(colors, 3));

  const material = new THREE.PointsMaterial({
    size: CONFIG.size || 2,
    vertexColors: true,
    transparent: true,
    opacity: CONFIG.opacity || 0.85,
    blending: THREE.AdditiveBlending,
    depthWrite: false,
    sizeAttenuation: true,
  });

  const points = new THREE.Points(geometry, material);
  scene.add(points);

  // === Animation Loop ===
  let time = 0;
  function animate() {
    requestAnimationFrame(animate);
    time += 0.016;
    
    const pos = geometry.attributes.position.array;
    for (let i = 0; i < count; i++) {
      const i3 = i * 3;
      // Simple noise-based movement
      pos[i3] += Math.sin(time + i * 0.01) * (CONFIG.speed || 0.3) * 0.01;
      pos[i3 + 1] += Math.cos(time + i * 0.01) * (CONFIG.speed || 0.3) * 0.01 - (CONFIG.gravity || 0) * 0.0001;
      pos[i3 + 2] += Math.sin(time * 0.5 + i * 0.02) * (CONFIG.speed || 0.3) * 0.005;
      
      // Boundary reset
      if (Math.abs(pos[i3]) > 50 || Math.abs(pos[i3 + 1]) > 50) {
        pos[i3] = (Math.random() - 0.5) * 60;
        pos[i3 + 1] = (Math.random() - 0.5) * 60;
      }
    }
    geometry.attributes.position.needsUpdate = true;
    renderer.render(scene, camera);
  }
  animate();

  // === Resize Handler ===
  window.addEventListener('resize', () => {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
  });
})();

/* 
  INTEGRATION GUIDE:
  1. Add to your HTML: <div id="particle-bg" style="position:fixed;inset:0;z-index:-1;"></div>
  2. Import this script as a module, or paste into a <script type="module"> tag
  3. Make sure Three.js is available (npm install three, or CDN)
  4. Your existing content will appear on top of the particle background
*/`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateExportCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSave = async () => {
    try {
      await apiRequest("POST", "/api/projects", {
        name: projectName,
        sourceUrl: sourceUrl || null,
        particleConfig: JSON.stringify(config),
        sequenceConfig: sequence.length > 0 ? JSON.stringify(sequence) : null,
        status: "completed",
        userId: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      });
      toast({ title: "Saved", description: "Project saved successfully" });
    } catch {
      toast({ title: "Saved locally", description: "Project configuration saved" });
    }
  };

  return (
    <div className="flex h-screen bg-gray-950 overflow-hidden" data-testid="builder-page">
      {/* Left panel — controls */}
      <div className="w-[380px] border-r border-white/8 flex flex-col bg-gray-950">
        {/* Header */}
        <div className="px-4 py-3 border-b border-white/8 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2">
            <button
              onClick={() => navigate("/dashboard")}
              className="text-white/40 hover:text-white transition-colors"
              data-testid="builder-back"
            >
              <ArrowLeft className="w-4 h-4" />
            </button>
            <input
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              className="bg-transparent text-white font-medium text-sm border-none outline-none w-40"
              data-testid="project-name-input"
            />
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="ghost" className="text-white/40 hover:text-white h-8 w-8 p-0" onClick={handleSave} data-testid="save-button">
              <Save className="w-4 h-4" />
            </Button>
            <Button size="sm" variant="ghost" className="text-white/40 hover:text-white h-8 w-8 p-0" onClick={() => setShowExport(true)} data-testid="export-button">
              <Download className="w-4 h-4" />
            </Button>
          </div>
        </div>

        {/* Tabs */}
        <Tabs defaultValue="particles" className="flex-1 flex flex-col min-h-0">
          <TabsList className="w-full shrink-0 bg-transparent border-b border-white/8 rounded-none justify-start px-4 gap-1">
            <TabsTrigger value="source" className="text-xs data-[state=active]:text-cyan-400 data-[state=active]:bg-cyan-400/10">Source</TabsTrigger>
            <TabsTrigger value="particles" className="text-xs data-[state=active]:text-cyan-400 data-[state=active]:bg-cyan-400/10">Particles</TabsTrigger>
            <TabsTrigger value="motion" className="text-xs data-[state=active]:text-cyan-400 data-[state=active]:bg-cyan-400/10">Motion</TabsTrigger>
            <TabsTrigger value="sequence" className="text-xs data-[state=active]:text-cyan-400 data-[state=active]:bg-cyan-400/10">Sequence</TabsTrigger>
          </TabsList>

          <ScrollArea className="flex-1">
            {/* SOURCE TAB */}
            <TabsContent value="source" className="p-4 space-y-6 mt-0">
              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Import existing page</Label>
                <div className="space-y-2">
                  <Input
                    value={sourceUrl}
                    onChange={(e) => setSourceUrl(e.target.value)}
                    placeholder="https://your-site.com/login"
                    className="bg-white/5 border-white/10 text-white text-sm placeholder:text-white/25"
                    data-testid="source-url-input"
                  />
                  <Button
                    size="sm"
                    variant="outline"
                    className="w-full border-white/10 text-white/60 hover:text-white text-xs gap-1.5"
                    data-testid="clone-page-button"
                  >
                    <Globe className="w-3.5 h-3.5" />
                    Clone page
                  </Button>
                </div>
              </div>

              <Separator className="bg-white/8" />

              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Background</Label>
                <div className="grid grid-cols-2 gap-2">
                  <Button
                    size="sm"
                    variant="outline"
                    className="border-white/10 text-white/60 text-xs gap-1.5 justify-start"
                    data-testid="remove-bg-button"
                  >
                    <Paintbrush className="w-3.5 h-3.5" />
                    Remove BG
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    className="border-white/10 text-white/60 text-xs gap-1.5 justify-start"
                    data-testid="use-existing-bg"
                  >
                    Existing BG
                  </Button>
                </div>
                <div className="flex items-center gap-2">
                  <label className="text-white/40 text-xs">Color:</label>
                  <input
                    type="color"
                    value={backgroundColor}
                    onChange={(e) => setBackgroundColor(e.target.value)}
                    className="w-8 h-8 rounded cursor-pointer bg-transparent border border-white/10"
                    data-testid="bg-color-picker"
                  />
                  <Input
                    value={backgroundColor}
                    onChange={(e) => setBackgroundColor(e.target.value)}
                    className="bg-white/5 border-white/10 text-white text-xs h-8 font-mono"
                    data-testid="bg-color-input"
                  />
                </div>
              </div>

              <Separator className="bg-white/8" />

              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Load preset</Label>
                <Select onValueChange={loadPreset}>
                  <SelectTrigger className="bg-white/5 border-white/10 text-white text-sm" data-testid="load-preset-select">
                    <SelectValue placeholder="Choose a preset" />
                  </SelectTrigger>
                  <SelectContent className="bg-gray-900 border-white/10">
                    {DEMO_PRESETS.map(p => (
                      <SelectItem key={p.id} value={p.id} className="text-white/80 focus:bg-white/10 focus:text-white">
                        {p.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </TabsContent>

            {/* PARTICLES TAB */}
            <TabsContent value="particles" className="p-4 space-y-5 mt-0">
              {/* Pattern */}
              <div className="space-y-2">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Pattern</Label>
                <Select
                  value={(activeConfig as ParticleConfig).pattern || "random"}
                  onValueChange={(v) => updateConfig({ pattern: v as ParticleConfig["pattern"] })}
                >
                  <SelectTrigger className="bg-white/5 border-white/10 text-white text-sm" data-testid="pattern-select">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-gray-900 border-white/10">
                    {["random", "array", "vortex", "orbit", "linear", "burst", "fireworks", "radiate", "rain", "snow"].map(p => (
                      <SelectItem key={p} value={p} className="text-white/80 focus:bg-white/10 focus:text-white capitalize">
                        {p}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Count */}
              <SliderControl
                label="Particle count"
                value={(activeConfig as ParticleConfig).count ?? 2000}
                min={100}
                max={10000}
                step={100}
                onChange={(v) => updateConfig({ count: v })}
                testId="slider-count"
              />

              {/* Size */}
              <SliderControl
                label="Particle size"
                value={(activeConfig as ParticleConfig).size ?? 2}
                min={0.5}
                max={10}
                step={0.5}
                onChange={(v) => updateConfig({ size: v })}
                testId="slider-size"
              />

              {/* Opacity */}
              <SliderControl
                label="Opacity"
                value={(activeConfig as ParticleConfig).opacity ?? 0.85}
                min={0.1}
                max={1}
                step={0.05}
                onChange={(v) => updateConfig({ opacity: v })}
                testId="slider-opacity"
              />

              <Separator className="bg-white/8" />

              {/* Colors */}
              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Colors</Label>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <label className="text-white/40 text-xs">Start</label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={(activeConfig as ParticleConfig).color || "#00d4ff"}
                        onChange={(e) => updateConfig({ color: e.target.value })}
                        className="w-8 h-8 rounded cursor-pointer bg-transparent border border-white/10"
                        data-testid="color-start"
                      />
                      <span className="text-white/40 text-xs font-mono">{(activeConfig as ParticleConfig).color}</span>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-white/40 text-xs">End</label>
                    <div className="flex items-center gap-2">
                      <input
                        type="color"
                        value={(activeConfig as ParticleConfig).gradientEnd || "#8b5cf6"}
                        onChange={(e) => updateConfig({ gradientEnd: e.target.value })}
                        className="w-8 h-8 rounded cursor-pointer bg-transparent border border-white/10"
                        data-testid="color-end"
                      />
                      <span className="text-white/40 text-xs font-mono">{(activeConfig as ParticleConfig).gradientEnd}</span>
                    </div>
                  </div>
                </div>
              </div>

              <Separator className="bg-white/8" />

              {/* Blending */}
              <div className="space-y-2">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Blending</Label>
                <Select
                  value={(activeConfig as ParticleConfig).blending || "additive"}
                  onValueChange={(v) => updateConfig({ blending: v as "additive" | "normal" })}
                >
                  <SelectTrigger className="bg-white/5 border-white/10 text-white text-sm" data-testid="blending-select">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="bg-gray-900 border-white/10">
                    <SelectItem value="additive" className="text-white/80 focus:bg-white/10 focus:text-white">Additive (glow)</SelectItem>
                    <SelectItem value="normal" className="text-white/80 focus:bg-white/10 focus:text-white">Normal</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {/* Grid-specific controls */}
              {(activeConfig as ParticleConfig).pattern === "array" && (
                <>
                  <Separator className="bg-white/8" />
                  <Label className="text-white/60 text-xs uppercase tracking-wider">Grid Settings</Label>
                  <SliderControl
                    label="Spacing"
                    value={(activeConfig as ParticleConfig).gridSpacing ?? 2}
                    min={0.5}
                    max={5}
                    step={0.5}
                    onChange={(v) => updateConfig({ gridSpacing: v })}
                    testId="slider-grid-spacing"
                  />
                  <SliderControl
                    label="Confinement"
                    value={(activeConfig as ParticleConfig).gridConfinement ?? 0.5}
                    min={0}
                    max={1}
                    step={0.05}
                    onChange={(v) => updateConfig({ gridConfinement: v })}
                    testId="slider-grid-confinement"
                  />
                </>
              )}
            </TabsContent>

            {/* MOTION TAB */}
            <TabsContent value="motion" className="p-4 space-y-5 mt-0">
              {/* Speed */}
              <SliderControl
                label="Speed"
                value={(activeConfig as ParticleConfig).speed ?? 0.3}
                min={0}
                max={3}
                step={0.1}
                onChange={(v) => updateConfig({ speed: v })}
                testId="slider-speed"
              />

              {/* Gravity */}
              <SliderControl
                label="Gravity"
                value={(activeConfig as ParticleConfig).gravity ?? 0}
                min={-2}
                max={2}
                step={0.1}
                onChange={(v) => updateConfig({ gravity: v })}
                testId="slider-gravity"
              />

              {/* Noise */}
              <SliderControl
                label="Noise intensity"
                value={(activeConfig as ParticleConfig).noiseIntensity ?? 0.5}
                min={0}
                max={3}
                step={0.1}
                onChange={(v) => updateConfig({ noiseIntensity: v })}
                testId="slider-noise"
              />

              <Separator className="bg-white/8" />

              {/* Wind */}
              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider flex items-center gap-1.5">
                  <Wind className="w-3.5 h-3.5" /> Wind
                </Label>
                <SliderControl
                  label="Wind power"
                  value={(activeConfig as ParticleConfig).windPower ?? 0}
                  min={0}
                  max={2}
                  step={0.1}
                  onChange={(v) => updateConfig({ windPower: v })}
                  testId="slider-wind-power"
                />
                <div className="grid grid-cols-3 gap-2">
                  <div className="space-y-1">
                    <label className="text-white/30 text-xs">X</label>
                    <Slider
                      value={[(activeConfig as ParticleConfig).windDirection?.x ?? 0]}
                      min={-1}
                      max={1}
                      step={0.1}
                      onValueChange={([v]) => updateConfig({ windDirection: { ...((activeConfig as ParticleConfig).windDirection || { x: 0, y: 0, z: 0 }), x: v } })}
                      data-testid="slider-wind-x"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-white/30 text-xs">Y</label>
                    <Slider
                      value={[(activeConfig as ParticleConfig).windDirection?.y ?? 0]}
                      min={-1}
                      max={1}
                      step={0.1}
                      onValueChange={([v]) => updateConfig({ windDirection: { ...((activeConfig as ParticleConfig).windDirection || { x: 0, y: 0, z: 0 }), y: v } })}
                      data-testid="slider-wind-y"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-white/30 text-xs">Z</label>
                    <Slider
                      value={[(activeConfig as ParticleConfig).windDirection?.z ?? 0]}
                      min={-1}
                      max={1}
                      step={0.1}
                      onValueChange={([v]) => updateConfig({ windDirection: { ...((activeConfig as ParticleConfig).windDirection || { x: 0, y: 0, z: 0 }), z: v } })}
                      data-testid="slider-wind-z"
                    />
                  </div>
                </div>
              </div>

              <Separator className="bg-white/8" />

              {/* Orbit */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <Label className="text-white/60 text-xs uppercase tracking-wider flex items-center gap-1.5">
                    <Orbit className="w-3.5 h-3.5" /> Scene orbit
                  </Label>
                  <Switch
                    checked={(activeConfig as ParticleConfig).orbitEnabled ?? false}
                    onCheckedChange={(v) => updateConfig({ orbitEnabled: v })}
                    data-testid="orbit-toggle"
                  />
                </div>
                {(activeConfig as ParticleConfig).orbitEnabled && (
                  <>
                    <SliderControl
                      label="Orbit speed"
                      value={(activeConfig as ParticleConfig).orbitSpeed ?? 0.2}
                      min={0}
                      max={2}
                      step={0.05}
                      onChange={(v) => updateConfig({ orbitSpeed: v })}
                      testId="slider-orbit-speed"
                    />
                    <div className="grid grid-cols-3 gap-2">
                      <div className="space-y-1">
                        <label className="text-white/30 text-xs">X axis</label>
                        <Slider
                          value={[(activeConfig as ParticleConfig).orbitAxis?.x ?? 0]}
                          min={0}
                          max={1}
                          step={0.1}
                          onValueChange={([v]) => updateConfig({ orbitAxis: { ...((activeConfig as ParticleConfig).orbitAxis || { x: 0, y: 1, z: 0 }), x: v } })}
                        />
                      </div>
                      <div className="space-y-1">
                        <label className="text-white/30 text-xs">Y axis</label>
                        <Slider
                          value={[(activeConfig as ParticleConfig).orbitAxis?.y ?? 1]}
                          min={0}
                          max={1}
                          step={0.1}
                          onValueChange={([v]) => updateConfig({ orbitAxis: { ...((activeConfig as ParticleConfig).orbitAxis || { x: 0, y: 1, z: 0 }), y: v } })}
                        />
                      </div>
                      <div className="space-y-1">
                        <label className="text-white/30 text-xs">Z axis</label>
                        <Slider
                          value={[(activeConfig as ParticleConfig).orbitAxis?.z ?? 0]}
                          min={0}
                          max={1}
                          step={0.1}
                          onValueChange={([v]) => updateConfig({ orbitAxis: { ...((activeConfig as ParticleConfig).orbitAxis || { x: 0, y: 1, z: 0 }), z: v } })}
                        />
                      </div>
                    </div>
                  </>
                )}
              </div>

              <Separator className="bg-white/8" />

              {/* Lifecycle */}
              <div className="space-y-3">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Lifecycle</Label>
                <div className="flex items-center justify-between">
                  <span className="text-white/40 text-xs">Regenerate</span>
                  <Switch
                    checked={(activeConfig as ParticleConfig).regenerate ?? true}
                    onCheckedChange={(v) => updateConfig({ regenerate: v })}
                    data-testid="regenerate-toggle"
                  />
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-white/40 text-xs">Loop back to origin</span>
                  <Switch
                    checked={(activeConfig as ParticleConfig).loopBack ?? false}
                    onCheckedChange={(v) => updateConfig({ loopBack: v })}
                    data-testid="loop-back-toggle"
                  />
                </div>
              </div>
            </TabsContent>

            {/* SEQUENCE TAB */}
            <TabsContent value="sequence" className="p-4 space-y-4 mt-0">
              <div className="space-y-2">
                <Label className="text-white/60 text-xs uppercase tracking-wider">Animation sequence</Label>
                <p className="text-white/25 text-xs leading-relaxed">
                  Add stops to create a multi-animation sequence with transitions between each.
                </p>
              </div>

              {/* Main animation */}
              <button
                className={`w-full text-left p-3 rounded-lg border transition-colors ${
                  activeSequenceIndex === -1
                    ? "bg-cyan-500/10 border-cyan-500/30"
                    : "bg-white/3 border-white/8 hover:border-white/15"
                }`}
                onClick={() => setActiveSequenceIndex(-1)}
                data-testid="sequence-main"
              >
                <div className="flex items-center justify-between">
                  <span className="text-white text-sm font-medium">Main animation</span>
                  <Badge variant="outline" className="border-cyan-500/30 text-cyan-400 text-xs">Active</Badge>
                </div>
                <span className="text-white/30 text-xs">{(config as ParticleConfig).pattern} pattern</span>
              </button>

              {/* Sequence stops */}
              {sequence.map((stop, idx) => (
                <div
                  key={stop.id}
                  className={`p-3 rounded-lg border transition-colors ${
                    activeSequenceIndex === idx
                      ? "bg-cyan-500/10 border-cyan-500/30"
                      : "bg-white/3 border-white/8 hover:border-white/15"
                  }`}
                >
                  <button
                    className="w-full text-left"
                    onClick={() => setActiveSequenceIndex(idx)}
                    data-testid={`sequence-stop-${idx}`}
                  >
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-white text-sm font-medium">Stop {idx + 1}</span>
                      <Button
                        size="sm"
                        variant="ghost"
                        className="h-6 w-6 p-0 text-white/20 hover:text-red-400"
                        onClick={(e) => { e.stopPropagation(); removeFromSequence(idx); }}
                        data-testid={`remove-stop-${idx}`}
                      >
                        <Trash2 className="w-3 h-3" />
                      </Button>
                    </div>
                    <span className="text-white/30 text-xs">
                      {(stop.config as ParticleConfig).pattern || "random"} — {stop.duration}s
                    </span>
                  </button>

                  {activeSequenceIndex === idx && (
                    <div className="mt-3 pt-3 border-t border-white/8 space-y-3">
                      <SliderControl
                        label="Duration (seconds)"
                        value={stop.duration}
                        min={1}
                        max={30}
                        step={0.5}
                        onChange={(v) => setSequence(prev => prev.map((s, i) => i === idx ? { ...s, duration: v } : s))}
                        testId={`slider-duration-${idx}`}
                      />
                      <div className="space-y-1">
                        <label className="text-white/40 text-xs">Transition</label>
                        <Select
                          value={stop.transition}
                          onValueChange={(v) => setSequence(prev => prev.map((s, i) => i === idx ? { ...s, transition: v as "fade" | "instant" | "flash" } : s))}
                        >
                          <SelectTrigger className="bg-white/5 border-white/10 text-white text-xs h-8">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent className="bg-gray-900 border-white/10">
                            <SelectItem value="fade" className="text-white/80 focus:bg-white/10 text-xs">Fade</SelectItem>
                            <SelectItem value="instant" className="text-white/80 focus:bg-white/10 text-xs">Instant</SelectItem>
                            <SelectItem value="flash" className="text-white/80 focus:bg-white/10 text-xs">Flash</SelectItem>
                          </SelectContent>
                        </Select>
                      </div>
                      <SliderControl
                        label="Transition time (s)"
                        value={stop.transitionDuration}
                        min={0}
                        max={5}
                        step={0.25}
                        onChange={(v) => setSequence(prev => prev.map((s, i) => i === idx ? { ...s, transitionDuration: v } : s))}
                        testId={`slider-transition-${idx}`}
                      />
                    </div>
                  )}
                </div>
              ))}

              <Button
                size="sm"
                variant="outline"
                className="w-full border-dashed border-white/15 text-white/40 hover:text-white gap-1.5"
                onClick={addToSequence}
                data-testid="add-sequence-stop"
              >
                <Plus className="w-3.5 h-3.5" />
                Add to sequence
              </Button>
            </TabsContent>
          </ScrollArea>
        </Tabs>
      </div>

      {/* Main canvas area */}
      <div className="flex-1 relative">
        <ParticleCanvas
          key={`${JSON.stringify(activeConfig)}-${activeBg}`}
          config={activeConfig}
          backgroundColor={activeBg}
        />

        {/* Floating controls */}
        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 z-10 flex items-center gap-2">
          <Button
            size="sm"
            variant="outline"
            className="bg-black/40 backdrop-blur-md border-white/15 text-white hover:bg-black/60 gap-1.5"
            onClick={() => {
              setConfig({ ...DEFAULT_CONFIG });
              setBackgroundColor("#0a0812");
            }}
            data-testid="reset-button"
          >
            <RotateCcw className="w-3.5 h-3.5" />
            Reset
          </Button>
        </div>
      </div>

      {/* Export dialog */}
      <Dialog open={showExport} onOpenChange={setShowExport}>
        <DialogContent className="bg-gray-900 border-white/10 max-w-2xl max-h-[80vh]">
          <DialogHeader>
            <DialogTitle className="text-white">Export code</DialogTitle>
            <DialogDescription className="text-white/50">
              Copy this Three.js code and add it to your project
            </DialogDescription>
          </DialogHeader>
          <ScrollArea className="h-[400px] rounded-lg">
            <pre className="bg-black/50 p-4 rounded-lg text-xs text-white/70 font-mono whitespace-pre overflow-x-auto">
              {generateExportCode()}
            </pre>
          </ScrollArea>
          <DialogFooter>
            <Button
              className="bg-cyan-500 hover:bg-cyan-400 text-black font-medium gap-1.5"
              onClick={handleCopy}
              data-testid="copy-code-button"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied" : "Copy code"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function SliderControl({
  label,
  value,
  min,
  max,
  step,
  onChange,
  testId,
}: {
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  onChange: (v: number) => void;
  testId: string;
}) {
  return (
    <div className="space-y-2">
      <div className="flex items-center justify-between">
        <label className="text-white/40 text-xs">{label}</label>
        <span className="text-white/50 text-xs font-mono">{value}</span>
      </div>
      <Slider
        value={[value]}
        min={min}
        max={max}
        step={step}
        onValueChange={([v]) => onChange(v)}
        data-testid={testId}
      />
    </div>
  );
}
