import type { ParticleConfig } from "./engine";

export interface DemoPreset {
  id: string;
  name: string;
  description: string;
  config: Partial<ParticleConfig>;
  backgroundColor: string;
}

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: "ember-rise",
    name: "Ember Rise",
    description: "Glowing embers floating upward from a warm hearth",
    config: {
      count: 1200,
      size: 1.8,
      color: "#ff6b35",
      gradientEnd: "#ffd700",
      pattern: "radiate",
      speed: 0.4,
      gravity: -0.3,
      noiseIntensity: 0.8,
      windDirection: { x: 0.2, y: 1, z: 0 },
      windPower: 0.3,
      opacity: 0.9,
      regenerate: true,
      loopBack: false,
      blending: "additive",
    },
    backgroundColor: "#0a0605",
  },
  {
    id: "cyber-rain",
    name: "Cyber Rain",
    description: "Digital rainfall in a neon-lit cityscape",
    config: {
      count: 2000,
      size: 1.2,
      color: "#00f5ff",
      gradientEnd: "#0066ff",
      pattern: "rain",
      speed: 1.2,
      gravity: 0.8,
      noiseIntensity: 0.1,
      windDirection: { x: 0.3, y: 0, z: 0 },
      windPower: 0.2,
      opacity: 0.7,
      regenerate: true,
      loopBack: false,
      blending: "additive",
    },
    backgroundColor: "#050a12",
  },
  {
    id: "nebula-vortex",
    name: "Nebula Vortex",
    description: "Spiraling cosmic dust forming a galactic vortex",
    config: {
      count: 1800,
      size: 1.6,
      color: "#8b5cf6",
      gradientEnd: "#ec4899",
      pattern: "vortex",
      speed: 0.6,
      gravity: 0,
      noiseIntensity: 0.4,
      windDirection: { x: 0, y: 0.1, z: 0 },
      windPower: 0.1,
      opacity: 0.85,
      regenerate: true,
      loopBack: true,
      orbitEnabled: true,
      orbitSpeed: 0.15,
      orbitAxis: { x: 0.1, y: 1, z: 0.1 },
      blending: "additive",
    },
    backgroundColor: "#080510",
  },
  {
    id: "crystal-grid",
    name: "Crystal Grid",
    description: "Geometric particle array with subtle oscillation",
    config: {
      count: 1600,
      size: 1.4,
      color: "#00d4ff",
      gradientEnd: "#00ff88",
      pattern: "array",
      speed: 0.2,
      gravity: 0,
      noiseIntensity: 0.6,
      windDirection: { x: 0, y: 0, z: 0 },
      windPower: 0,
      gridSpacing: 2.5,
      gridConfinement: 0.3,
      opacity: 0.8,
      regenerate: false,
      loopBack: true,
      orbitEnabled: true,
      orbitSpeed: 0.1,
      orbitAxis: { x: 0.3, y: 1, z: 0.2 },
      blending: "additive",
    },
    backgroundColor: "#030812",
  },
  {
    id: "cosmic-orbit",
    name: "Cosmic Orbit",
    description: "Particles orbiting in concentric rings",
    config: {
      count: 1500,
      size: 1.5,
      color: "#fbbf24",
      gradientEnd: "#f472b6",
      pattern: "orbit",
      speed: 0.8,
      gravity: 0,
      noiseIntensity: 0.3,
      windDirection: { x: 0, y: 0.1, z: 0 },
      windPower: 0.05,
      opacity: 0.85,
      regenerate: true,
      loopBack: true,
      orbitEnabled: true,
      orbitSpeed: 0.25,
      orbitAxis: { x: 0.2, y: 1, z: 0 },
      blending: "additive",
    },
    backgroundColor: "#0a0510",
  },
];
